api/urls.py
from django.urls import path
from api import views

app_name = "api"

urlpatterns = [
    ### Menu ###
    path('', views.DeveloperMenuView.as_view(), name="developer_menu"),

    #### User ####
    path('users/', views.UserList.as_view(), name="user_list"),
    path('users/<int:pk>/', views.UserDetail.as_view(), name="user_detail"),
    path('users/create/', views.CreateUser.as_view(), name="create_user"),   
    path('users/update/<int:pk>/', views.UpdateUser.as_view(), name="update_user"),
    path('users/delete/<int:pk>/', views.DeleteUser.as_view(), name="delete_user"),
    
    #### Artist ####
    path('artists/', views.ArtistList.as_view(), name="artist_list"),
    path('artists/<int:pk>/', views.ArtistDetail.as_view(), name="artist_detail"),
    path('artists/create/', views.CreateArtist.as_view(), name="create_artist"),
    path('artists/update/<int:pk>/', views.UpdateArtist.as_view(), name="update_artist"),
    path('artists/delete/<int:pk>/', views.DeleteArtist.as_view(), name="delete_artist"),

    #### Profile ####
    path('profiles/', views.ProfileList.as_view(), name="profile_list"),
    path('profiles/<int:pk>/', views.ProfileDetail.as_view(), name="profile_detail"),
    path('profiles/update/<int:pk>/', views.UpdateProfile.as_view(), name="update_profile"),

    #### Country ####
    path('countries/', views.CountryList.as_view(), name="country_list"),
    path('countries/<int:pk>/', views.CountryDetail.as_view(), name="country_detail"),
    path('countries/create/', views.CreateCountry.as_view(), name="create_country"),
    path('countries/update/<int:pk>/', views.UpdateCountry.as_view(), name="update_country"),
    path('countries/delete/<int:pk>/', views.DeleteCountry.as_view(), name="delete_country"),

    #### Genre ####
    path('genres/', views.GenreList.as_view(), name="genre_list"),
    path('genres/<int:pk>/', views.GenreDetail.as_view(), name="genre_detail"),
    path('genres/create/', views.CreateGenre.as_view(), name="create_genre"),
    path('genres/update/<int:pk>/', views.UpdateGenre.as_view(), name="update_genre"),
    path('genres/delete/<int:pk>/', views.DeleteGenre.as_view(), name="delete_genre"),

    #### Album ####
    path('albums/', views.AlbumList.as_view(), name="album_list"),
    path('albums/<int:pk>/', views.AlbumDetail.as_view(), name="album_detail"),
    path('albums/create/', views.CreateAlbum.as_view(), name="create_album"),
    path('albums/update/<int:pk>/', views.UpdateAlbum.as_view(), name="update_album"),
    path('albums/delete/<int:pk>/', views.DeleteAlbum.as_view(), name="delete_album"),

    #### Song ####
    path('songs/', views.SongList.as_view(), name="song_list"),
    path('songs/<int:pk>/', views.SongDetail.as_view(), name="song_detail"),
    path('songs/create/', views.CreateSong.as_view(), name="create_song"),
    path('songs/update/<int:pk>/', views.UpdateSong.as_view(), name="update_song"),
    path('songs/delete/<int:pk>/', views.DeleteSong.as_view(), name="delete_song"),

    #### Playlist ####
    path('playlists/', views.PlaylistList.as_view(), name="playlist_list"),
    path('playlists/<int:pk>/', views.PlaylistDetail.as_view(), name="playlist_detail"),
    path('playlists/create/', views.CreatePlaylist.as_view(), name="create_playlist"),
    path('playlists/update/<int:pk>/', views.UpdatePlaylist.as_view(), name="update_playlist"),
    path('playlists/delete/<int:pk>/', views.DeletePlaylist.as_view(), name="delete_playlist"),

    #### Disc ####
    path('discs/', views.DiscList.as_view(), name="disc_list"),
    path('discs/<int:pk>/', views.DiscDetail.as_view(), name="disc_detail"),
    path('discs/create/', views.CreateDisc.as_view(), name="create_disc"),
    path('discs/update/<int:pk>/', views.UpdateDisc.as_view(), name="update_disc"),
    path('discs/delete/<int:pk>/', views.DeleteDisc.as_view(), name="delete_disc"),

    #### Like ####
    path('likes/', views.LikeList.as_view(), name="like_list"),
    path('likes/<int:pk>/', views.LikeDetail.as_view(), name="like_detail"),
    path('likes/create/', views.CreateLike.as_view(), name="create_like"),
    path('likes/update/<int:pk>/', views.UpdateLike.as_view(), name="update_like"),
    path('likes/delete/<int:pk>/', views.DeleteLike.as_view(), name="delete_like"),
]


god/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')), 
    path('api/', include('api.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.hashers import make_password
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.contrib import messages
from main.models import *
from api.forms import *
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

### MENU

class DeveloperMenuView(View):
    template_name = 'api/developer_menu.html'

    def get(self, request, *args, **kwargs):
        last_artists = Artist.objects.order_by('-id')[:5]

        context = {
            'last_artists': last_artists,
        }

        return render(request, self.template_name, context)

### USER

class UserList(ListView):
    model = User
    template_name = "api/user/user_list.html"

    def get_queryset(self):
        queryset = User.objects.all()
        search_query = self.request.GET.get('search', None)
        if search_query:
            queryset = queryset.filter(
                Q(id__icontains=search_query)
            )
        return queryset

class UserDetail(DetailView):
    model = User
    template_name = "api/user/user_detail.html"

class CreateUser(SuccessMessageMixin, CreateView):
    model = User
    form_class = CreateUserForm
    template_name = 'api/user/create_user.html'
    success_url = reverse_lazy('api:user_list')
    success_message = "User and Profile successfully created!"
    
    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        return response

class UpdateUser(SuccessMessageMixin, UpdateView):
    model = User
    form_class = CreateUserForm
    template_name = "api/user/update_user.html"
    success_url = reverse_lazy("api:user_list")
    success_message = "User successfully updated!"

class DeleteUser(DeleteView):
    model = User
    template_name = "api/user/delete_user.html"
    success_url = reverse_lazy("api:user_list")

### COUNTRY

class CountryList(ListView):
    model = Country
    template_name = "api/country/country_list.html"

    def get_queryset(self):
        queryset = Country.objects.all()
        search_query = self.request.GET.get('search', None)
        if search_query:
            queryset = queryset.filter(
                Q(id__icontains=search_query) |
                Q(name__icontains=search_query) |
                Q(abbreviation__icontains=search_query)
            )
        return queryset

class CountryDetail(DetailView):
    model = Country
    template_name = "api/country/country_detail.html"

class CreateCountry(SuccessMessageMixin, CreateView):
    model = Country
    form_class = CreateCountryForm
    template_name = "api/country/create_country.html"
    success_url = reverse_lazy("api:country_list")
    success_message = "Country successfully created!"

class UpdateCountry(SuccessMessageMixin, UpdateView):
    model = Country
    form_class = CreateCountryForm
    template_name = "api/country/update_country.html"
    success_url = reverse_lazy("api:country_list")
    success_message = "Country successfully updated!"

class DeleteCountry(DeleteView):
    model = Country
    template_name = "api/country/delete_country.html"
    success_url = reverse_lazy("api:country_list")


### PROFILE

class ProfileList(ListView):
    model = Profile
    template_name = "api/profile/profile_list.html"

    def get_queryset(self):
        queryset = Profile.objects.all()
        search_query = self.request.GET.get('search', None)
        if search_query:
            queryset = queryset.filter(
                Q(id__icontains=search_query) |
                Q(user__username__icontains=search_query) |
                Q(biography__icontains=search_query)
            )
        return queryset

class ProfileDetail(DetailView):
    model = Profile
    template_name = "api/profile/profile_detail.html"

class UpdateProfile(SuccessMessageMixin, UpdateView):
    model = Profile
    form_class = CreateProfileForm
    template_name = "api/profile/update_profile.html"
    success_url = reverse_lazy("api:profile_list")
    success_message = "Profile successfully updated!"

class DeleteProfile(DeleteView):
    model = Profile
    template_name = "api/profile/delete_profile.html"
    success_url = reverse_lazy("api:profile_list")

### GENRE

class GenreList(ListView):
    model = Genre
    template_name = "api/genre/genre_list.html"

    def get_queryset(self):
        queryset = Genre.objects.all()
        search_query = self.request.GET.get('search', None)
        if search_query:
            queryset = queryset.filter(
                Q(id__icontains=search_query) |
                Q(name__icontains=search_query) |
                Q(description__icontains=search_query)
            )
        return queryset

class GenreDetail(DetailView):
    model = Genre
    template_name = "api/genre/genre_detail.html"

class CreateGenre(SuccessMessageMixin, CreateView):
    model = Genre
    form_class = CreateGenreForm
    template_name = "api/genre/create_genre.html"
    success_url = reverse_lazy("api:genre_list")
    success_message = "Genre successfully created!"

class UpdateGenre(SuccessMessageMixin, UpdateView):
    model = Genre
    form_class = CreateGenreForm
    template_name = "api/genre/update_genre.html"
    success_url = reverse_lazy("api:genre_list")
    success_message = "Genre successfully updated!"

class DeleteGenre(DeleteView):
    model = Genre
    template_name = "api/genre/delete_genre.html"
    success_url = reverse_lazy("api:genre_list")


### ARTIST

class ArtistList(ListView):
    model = Artist
    template_name = "api/artist/artist_list.html"

    def get_queryset(self):
        queryset = Artist.objects.all()
        search_query = self.request.GET.get('search', None)
        if search_query:
            queryset = queryset.filter(
                Q(id__icontains=search_query) |
                Q(name__icontains=search_query) |
                Q(nickname__icontains=search_query)
            )
        return queryset

class ArtistDetail(DetailView):
    model = Artist
    template_name = "api/artist/artist_detail.html"

class CreateArtist(SuccessMessageMixin, CreateView):
    model = Artist
    form_class = CreateArtistForm
    template_name = "api/artist/create_artist.html"
    success_url = reverse_lazy("api:artist_list")
    success_message = "Artist successfully created!"
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, self.success_message)
        return response

    def form_invalid(self, form):
        print(form.errors)
        return super().form_invalid(form)

class UpdateArtist(SuccessMessageMixin, UpdateView):
    model = Artist
    form_class = CreateArtistForm
    template_name = "api/artist/update_artist.html"
    success_url = reverse_lazy("api:artist_list")
    success_message = "Artist successfully updated!"

class DeleteArtist(DeleteView):
    model = Artist
    template_name = "api/artist/delete_artist.html"
    success_url = reverse_lazy("api:artist_list")

### ALBUM

class AlbumList(ListView):
    model = Album
    template_name = "api/album/album_list.html"

    def get_queryset(self):
        queryset = Album.objects.all()
        search_query = self.request.GET.get('search', None)
        if search_query:
            queryset = queryset.filter(
                Q(id__icontains=search_query) |
                Q(title__icontains=search_query) |
                Q(description__icontains=search_query)
            )
        return queryset

class AlbumDetail(DetailView):
    model = Album
    template_name = "api/album/album_detail.html"

class CreateAlbum(SuccessMessageMixin, CreateView):
    model = Album
    form_class = CreateAlbumForm
    template_name = "api/album/create_album.html"
    success_url = reverse_lazy("api:album_list")
    success_message = "Album successfully created!"

class UpdateAlbum(SuccessMessageMixin, UpdateView):
    model = Album
    form_class = CreateAlbumForm
    template_name = "api/album/update_album.html"
    success_url = reverse_lazy("api:album_list")
    success_message = "Album successfully updated!"

class DeleteAlbum(DeleteView):
    model = Album
    template_name = "api/album/delete_album.html"
    success_url = reverse_lazy("api:album_list")

# SONG

class SongList(ListView):
    model = Song
    template_name = "api/song/song_list.html"

    def get_queryset(self):
        queryset = Song.objects.all()
        
        search_query = self.request.GET.get('search', None)
        if search_query:
            queryset = queryset.filter(
                Q(id__icontains=search_query) |
                Q(title__icontains=search_query) |
                Q(duration__icontains=search_query)
            )
        return queryset

class SongDetail(DetailView):
    model = Song
    template_name = "api/song/song_detail.html"

class CreateSong(SuccessMessageMixin, CreateView):
    model = Song
    form_class = CreateSongForm
    template_name = "api/song/create_song.html"
    success_url = reverse_lazy("api:song_list")
    success_message = "Song successfully created!"

class UpdateSong(SuccessMessageMixin, UpdateView):
    model = Song
    form_class = CreateSongForm
    template_name = "api/song/update_song.html"
    success_url = reverse_lazy("api:song_list")
    success_message = "Song successfully updated!"

class DeleteSong(DeleteView):
    model = Song

templates/api/disc/create_disc.html
{% extends "base/base.html" %}

{% block title %}
    Create Disc
{% endblock title %}

{% block content %}
    <h2>Create Disc</h2>
    <div class="row">
        <div class="col-md-6">
            <form method="post" action="">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Create Disc</button>
                <a href="{% url 'api:disc_list' %}" class="btn btn-secondary">Disc List</a>
            </form>
        </div>
    </div>
{% endblock content %}






templates/api/disc/delete_disc.html
{% extends "base/base.html" %}

{% block title %}
    Delete Disc
{% endblock title %}

{% block content %}
    <h2>Delete Disc</h2>
    <p>Are you sure you want to delete the disc '{{ disc.title }}'?</p>
    <form method="post" action="">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'api:disc_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock content %}


templates/api/disc/disc_detail.html
{% extends "base/base.html" %}

{% block title %}
    Disc Detail
{% endblock title %}

{% block content %}
    <div class="container mt-4">
        <h2>Disc Detail</h2>
        <dl class="row">
            <dt class="col-sm-3">ID:</dt>
            <dd class="col-sm-9">{{ disc.id }}</dd>

            <dt class="col-sm-3">User:</dt>
            <dd class="col-sm-9">{{ disc.user }}</dd>

            <dt class="col-sm-3">Title:</dt>
            <dd class="col-sm-9">{{ disc.title }}</dd>

            <dt class="col-sm-3">Genres:</dt>
            <dd class="col-sm-9">
                {% for genre in disc.genres.all %}
                  {{ genre.name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
              </dd>

            <dt class="col-sm-3">Duration:</dt>
            <dd class="col-sm-9">{{ disc.duration }}</dd>

            <dt class="col-sm-3">Video:</dt>
            <dd class="col-sm-9">{{ disc.video }}</dd>
        </dl>

        <a href="{% url 'api:disc_list' %}" class="btn btn-secondary">Back to Disc List</a>
    </div>
{% endblock content %}


templates/api/disc/disc_list.html
{% extends "base/base.html" %}

{% block title %}
    Disc List
{% endblock title %}

{% block content %}
    <div class="container d-flex align-items-center justify-content-between">
        <h2 class="text-center mb-2">Disc List</h2>
        <div class="d-flex align-items-center">
            <form class="form-inline" method="GET" action="{% url 'api:disc_list' %}">
                <div class="input-group">
                    <input type="text" class="form-control" name="search" placeholder="Search">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-secondary" style="margin-right: 20px;">Search</button>
                    </div>
                </div>
            </form>
            <a href="{% url 'api:create_disc' %}" class="btn btn-primary ml-2">Create</a>
        </div>
    </div>
    <h1></h1>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead class="bg-dark text-light">
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">User</th>
                    <th class="text-center">Title</th>
                    <th class="text-center">Genres</th>
                    <th class="text-center">Duration</th>
                    <th class="text-center">Video</th>
                    <th class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for disc in object_list %}
                    <tr class="{% cycle 'table-dark' 'table-secondary' %}">
                        <td class="text-center">{{ disc.id }}</td>
                        <td class="text-center">{{ disc.user }}</td>
                        <td class="text-center">{{ disc.title }}</td>
                        <td class="text-center">
                            {% for genre in disc.genres.all %}
                                {{ genre.name }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </td>     
                        <td class="text-center">{{ disc.duration }}</td>
                        <td class="text-center">{{ disc.video }}</td>
                        <td class="text-center">
                            <a href="{% url 'api:update_disc' pk=disc.id %}" class="btn btn-warning btn-sm" style="margin-right: 10px;">Update</a>
                            <a href="{% url 'api:disc_detail' pk=disc.id %}" class="btn btn-info btn-sm" style="margin-right: 10px;">Detail</a>
                            <a href="{% url 'api:delete_disc' pk=disc.id %}" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}






templates/api/disc/update_disc.html
{% extends "base/base.html" %}

{% block title %}
    Update Disc
{% endblock title %}

{% block content %}
    <h2>Update Disc</h2>
    <div class="row">
        <div class="col-md-6">
            <form method="post" action="">
                {% csrf_token %}
                <input type="hidden" name="_method" value="put">
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Update Disc</button>
                <a href="{% url 'api:disc_list' %}" class="btn btn-secondary">Disc List</a>
            </form>
        </div>
    </div>
{% endblock content %}

