api/urls.py
from django.urls import path
from api import views

app_name = "api"

urlpatterns = [
    ### Menu ###
    path('', views.DeveloperMenuView.as_view(), name="developer_menu"),

    #### User ####
    path('users/', views.UserList.as_view(), name="user_list"),
    path('users/<int:pk>/', views.UserDetail.as_view(), name="user_detail"),
    path('users/create/', views.CreateUser.as_view(), name="create_user"),   
    path('users/update/<int:pk>/', views.UpdateUser.as_view(), name="update_user"),
    path('users/delete/<int:pk>/', views.DeleteUser.as_view(), name="delete_user"),
    
    #### Artist ####
    path('artists/', views.ArtistList.as_view(), name="artist_list"),
    path('artists/<int:pk>/', views.ArtistDetail.as_view(), name="artist_detail"),
    path('artists/create/', views.CreateArtist.as_view(), name="create_artist"),
    path('artists/update/<int:pk>/', views.UpdateArtist.as_view(), name="update_artist"),
    path('artists/delete/<int:pk>/', views.DeleteArtist.as_view(), name="delete_artist"),

    #### Profile ####
    path('profiles/', views.ProfileList.as_view(), name="profile_list"),
    path('profiles/<int:pk>/', views.ProfileDetail.as_view(), name="profile_detail"),
    path('profiles/update/<int:pk>/', views.UpdateProfile.as_view(), name="update_profile"),

    #### Country ####
    path('countries/', views.CountryList.as_view(), name="country_list"),
    path('countries/<int:pk>/', views.CountryDetail.as_view(), name="country_detail"),
    path('countries/create/', views.CreateCountry.as_view(), name="create_country"),
    path('countries/update/<int:pk>/', views.UpdateCountry.as_view(), name="update_country"),
    path('countries/delete/<int:pk>/', views.DeleteCountry.as_view(), name="delete_country"),

    #### Genre ####
    path('genres/', views.GenreList.as_view(), name="genre_list"),
    path('genres/<int:pk>/', views.GenreDetail.as_view(), name="genre_detail"),
    path('genres/create/', views.CreateGenre.as_view(), name="create_genre"),
    path('genres/update/<int:pk>/', views.UpdateGenre.as_view(), name="update_genre"),
    path('genres/delete/<int:pk>/', views.DeleteGenre.as_view(), name="delete_genre"),

    #### Album ####
    path('albums/', views.AlbumList.as_view(), name="album_list"),
    path('albums/<int:pk>/', views.AlbumDetail.as_view(), name="album_detail"),
    path('albums/create/', views.CreateAlbum.as_view(), name="create_album"),
    path('albums/update/<int:pk>/', views.UpdateAlbum.as_view(), name="update_album"),
    path('albums/delete/<int:pk>/', views.DeleteAlbum.as_view(), name="delete_album"),

    #### Song ####
    path('songs/', views.SongList.as_view(), name="song_list"),
    path('songs/<int:pk>/', views.SongDetail.as_view(), name="song_detail"),
    path('songs/create/', views.CreateSong.as_view(), name="create_song"),
    path('songs/update/<int:pk>/', views.UpdateSong.as_view(), name="update_song"),
    path('songs/delete/<int:pk>/', views.DeleteSong.as_view(), name="delete_song"),

    #### Playlist ####
    path('playlists/', views.PlaylistList.as_view(), name="playlist_list"),
    path('playlists/<int:pk>/', views.PlaylistDetail.as_view(), name="playlist_detail"),
    path('playlists/create/', views.CreatePlaylist.as_view(), name="create_playlist"),
    path('playlists/update/<int:pk>/', views.UpdatePlaylist.as_view(), name="update_playlist"),
    path('playlists/delete/<int:pk>/', views.DeletePlaylist.as_view(), name="delete_playlist"),

    #### Disc ####
    path('discs/', views.DiscList.as_view(), name="disc_list"),
    path('discs/<int:pk>/', views.DiscDetail.as_view(), name="disc_detail"),
    path('discs/create/', views.CreateDisc.as_view(), name="create_disc"),
    path('discs/update/<int:pk>/', views.UpdateDisc.as_view(), name="update_disc"),
    path('discs/delete/<int:pk>/', views.DeleteDisc.as_view(), name="delete_disc"),

    #### Like ####
    path('likes/', views.LikeList.as_view(), name="like_list"),
    path('likes/<int:pk>/', views.LikeDetail.as_view(), name="like_detail"),
    path('likes/create/', views.CreateLike.as_view(), name="create_like"),
    path('likes/update/<int:pk>/', views.UpdateLike.as_view(), name="update_like"),
    path('likes/delete/<int:pk>/', views.DeleteLike.as_view(), name="delete_like"),
]


god/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')), 
    path('api/', include('api.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mania{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'api:developer_menu' %}">Mania</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'api:user_list' %}">User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'api:profile_list' %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'api:country_list' %}">Country</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'api:genre_list' %}">Genre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'api:artist_list' %}">Artist</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'api:album_list' %}">Album</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'api:playlist_list' %}">Playlist</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'api:song_list' %}">Song</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'api:disc_list' %}">Disc</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'api:like_list' %}">Like</a>
                        </li>
                        <div class="d-flex">
                            <a class="nav-link" href="/logout">Log Out</a>
                        </div>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="row mt-3">
            <div class="col">
                <h1>{% block header %}{% endblock header %}</h1>
            </div>
        </div>

        {% block content %}
        {% endblock content %}
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>
