api/urls.py
from django.urls import path
from api import views

app_name = "api"

urlpatterns = [
    ### Menu ###
    path('', views.DeveloperMenuView.as_view(), name="developer_menu"),

    #### User ####
    path('users/', views.UserList.as_view(), name="user_list"),
    path('users/<int:pk>/', views.UserDetail.as_view(), name="user_detail"),
    path('users/create/', views.CreateUser.as_view(), name="create_user"),   
    path('users/update/<int:pk>/', views.UpdateUser.as_view(), name="update_user"),
    path('users/delete/<int:pk>/', views.DeleteUser.as_view(), name="delete_user"),
    
    #### Artist ####
    path('artists/', views.ArtistList.as_view(), name="artist_list"),
    path('artists/<int:pk>/', views.ArtistDetail.as_view(), name="artist_detail"),
    path('artists/create/', views.CreateArtist.as_view(), name="create_artist"),
    path('artists/update/<int:pk>/', views.UpdateArtist.as_view(), name="update_artist"),
    path('artists/delete/<int:pk>/', views.DeleteArtist.as_view(), name="delete_artist"),

    #### Profile ####
    path('profiles/', views.ProfileList.as_view(), name="profile_list"),
    path('profiles/<int:pk>/', views.ProfileDetail.as_view(), name="profile_detail"),
    path('profiles/update/<int:pk>/', views.UpdateProfile.as_view(), name="update_profile"),

    #### Country ####
    path('countries/', views.CountryList.as_view(), name="country_list"),
    path('countries/<int:pk>/', views.CountryDetail.as_view(), name="country_detail"),
    path('countries/create/', views.CreateCountry.as_view(), name="create_country"),
    path('countries/update/<int:pk>/', views.UpdateCountry.as_view(), name="update_country"),
    path('countries/delete/<int:pk>/', views.DeleteCountry.as_view(), name="delete_country"),

    #### Genre ####
    path('genres/', views.GenreList.as_view(), name="genre_list"),
    path('genres/<int:pk>/', views.GenreDetail.as_view(), name="genre_detail"),
    path('genres/create/', views.CreateGenre.as_view(), name="create_genre"),
    path('genres/update/<int:pk>/', views.UpdateGenre.as_view(), name="update_genre"),
    path('genres/delete/<int:pk>/', views.DeleteGenre.as_view(), name="delete_genre"),

    #### Album ####
    path('albums/', views.AlbumList.as_view(), name="album_list"),
    path('albums/<int:pk>/', views.AlbumDetail.as_view(), name="album_detail"),
    path('albums/create/', views.CreateAlbum.as_view(), name="create_album"),
    path('albums/update/<int:pk>/', views.UpdateAlbum.as_view(), name="update_album"),
    path('albums/delete/<int:pk>/', views.DeleteAlbum.as_view(), name="delete_album"),

    #### Song ####
    path('songs/', views.SongList.as_view(), name="song_list"),
    path('songs/<int:pk>/', views.SongDetail.as_view(), name="song_detail"),
    path('songs/create/', views.CreateSong.as_view(), name="create_song"),
    path('songs/update/<int:pk>/', views.UpdateSong.as_view(), name="update_song"),
    path('songs/delete/<int:pk>/', views.DeleteSong.as_view(), name="delete_song"),

    #### Playlist ####
    path('playlists/', views.PlaylistList.as_view(), name="playlist_list"),
    path('playlists/<int:pk>/', views.PlaylistDetail.as_view(), name="playlist_detail"),
    path('playlists/create/', views.CreatePlaylist.as_view(), name="create_playlist"),
    path('playlists/update/<int:pk>/', views.UpdatePlaylist.as_view(), name="update_playlist"),
    path('playlists/delete/<int:pk>/', views.DeletePlaylist.as_view(), name="delete_playlist"),

    #### Disc ####
    path('discs/', views.DiscList.as_view(), name="disc_list"),
    path('discs/<int:pk>/', views.DiscDetail.as_view(), name="disc_detail"),
    path('discs/create/', views.CreateDisc.as_view(), name="create_disc"),
    path('discs/update/<int:pk>/', views.UpdateDisc.as_view(), name="update_disc"),
    path('discs/delete/<int:pk>/', views.DeleteDisc.as_view(), name="delete_disc"),

    #### Like ####
    path('likes/', views.LikeList.as_view(), name="like_list"),
    path('likes/<int:pk>/', views.LikeDetail.as_view(), name="like_detail"),
    path('likes/create/', views.CreateLike.as_view(), name="create_like"),
    path('likes/update/<int:pk>/', views.UpdateLike.as_view(), name="update_like"),
    path('likes/delete/<int:pk>/', views.DeleteLike.as_view(), name="delete_like"),
]


god/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')), 
    path('api/', include('api.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path
from main import views
from api import views as apiview

app_name = 'main'

urlpatterns = [
    ### General ####
    path('' , views.SignupPage , name='signup'),
    path('login/' , views.LoginPage , name='login'),
    path('search/',views.SearchList , name='search'),
    path('album/list/', views.AlbumList, name='album_list'),
    path('api/developer_menu' , views.AdminPage , name='developer_menu'),
    path('like/list/' , views.LikeList , name='like_list'),
    path('like/create/' , views.CreateLike , name='create_like'),
    path('logout/' , views.LogoutPage , name='logout'),
    
    ### Info ###
    path('profile/', views.ProfileDetail, name='profile'),
    path('profile/update/', views.UpdateProfile, name='update_profile'),
    path('artist/detail/<int:pk>/', views.ArtistDetail, name='artist_detail'),
    path('genre/detail/<int:pk>/', views.GenreDetail, name='genre_detail'),
    path('album/detail/<int:pk>/', views.AlbumDetail, name='album_detail'),
    path('country/detail/<int:pk>/', views.CountryDetail, name='country_detail'),
    
    ### PlayList ###
    path('playlist/list/', views.PlaylistList, name="playlist_list"),
    path('playlist/detail/<int:pk>/', views.PlaylistDetail, name="playlist_detail"),
    path('playlist/create/', views.CreatePlaylist, name="create_playlist"),
    path('playlist/update/<int:pk>/', views.UpdatePlaylist, name="update_playlist"),
    path('playlist/delete/<int:pk>/', views.DeletePlaylist, name="delete_playlist"),

    ### Disc ###
    path('disc/list/', views.DiscList, name="disc_list"),
    path('Disc/<int:pk>/', views.DiscDetail, name="disc_detail"),
    path('Disc/create/', views.CreateDisc, name="create_disc"),
    path('Disc/update/<int:pk>/', views.UpdateDisc, name="update_disc"),
    path('Disc/delete/<int:pk>/', views.DeleteDisc, name="delete_disc"),
]

main/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from youtube_search import YoutubeSearch
import json
from django.http import JsonResponse
from .forms import *
from .models import *
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q

# Create your views here.
@login_required(login_url='login')
def AdminPage(request):
    return render (request,'api/developer_menu.html')

def SignupPage(request):
    if request.method=='POST':
        uname = request.POST.get('username')
        email = request.POST.get('email')
        pass1 = request.POST.get('password1')
        pass2 = request.POST.get('password2')

        if pass1!=pass2:
            error_message = "Your password's are not the same!!"
            return render(request, 'main/signup.html', {'error_message': error_message})
            #return HttpResponse("Your password and confrom password are not Same!!")
        else:
            my_user = User.objects.create_user(uname,email,pass1)
            my_user.save()
            profile = Profile(user=my_user)
            profile.save()
            return redirect('main:login')
    return render (request,'main/signup.html')

def LoginPage(request):
    if request.method=='POST':
        username=request.POST.get('username')
        pass1=request.POST.get('pass')
        user=authenticate(request,username=username,password=pass1)
        if user is not None:
            login(request,user)
            if user.is_staff:
                return redirect('api:developer_menu')
            else:
                return redirect('main:album_list') 
            #return redirect('home')
        else:
            error_message = "Username or Password is incorrect!!"
            return render(request, 'main/login.html', {'error_message': error_message})
            #return HttpResponse ("Username or Password is incorrect!!!")

    return render (request,'main/login.html')

def LogoutPage(request):
    logout(request)
    return redirect('main:login')

@login_required
def ProfileDetail(request):
    user = request.user
    profile = Profile.objects.get(user=user)

    context = {
        'user': user,
        'profile': profile,
    }

    return render(request, 'main/profile.html', context)

def UpdateProfile(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            # Redirect to the profile page or wherever you want
            return redirect('main:profile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    return render(request, 'main/update_profile.html', {'user_form': user_form, 'profile_form': profile_form})

def ArtistDetail(request):
    artists = Artist.objects.all()
    return render(request, 'main/artist_detail.html', {'artists': artists})

def AlbumList(request):
    # Obtén todos los géneros disponibles
    genres = Genre.objects.all()
    albums = Album.objects.all()
    albums_by_genre = {}
    for genre in genres:
        albums_by_genre[genre.name] = Album.objects.filter(genres=genre)

    albums_with_song_ids = []
    for album in albums:
        song_ids = album.get_all_video_ids()
        albums_with_song_ids.append({'album': album, 'song_ids': song_ids})

    return render(request, 'main/album_list.html', {'albums_with_song_ids': albums_with_song_ids, 'albums_by_genre': albums_by_genre})
    #return render(request, 'main/album_list.html', {'albums_by_genre': albums_by_genre})

@login_required
def PlaylistList(request):
    playlists = Playlist.objects.filter(user=request.user)
    return render(request, 'main/playlist_list.html', {'playlists': playlists})

def CreatePlaylist(request):
    if request.method == 'POST':
        playlist_form = PlaylistCreateForm(request.POST, request.FILES)

        if playlist_form.is_valid():
            playlist = playlist_form.save(commit=False)
            playlist.user = request.user
            playlist.save()
            playlist_form.save_m2m()
            return redirect('main:playlist_list')
    else:
        playlist_form = PlaylistCreateForm()

    return render(request, 'main/create_playlist.html', {'playlist_form': playlist_form})


def PlaylistDetail(request, pk):
    playlist = get_object_or_404(Playlist, pk=pk)
    return render(request, 'main/playlist_detail.html', {'playlist': playlist})

def UpdatePlaylist(request, pk):
    playlist = get_object_or_404(Playlist, pk=pk)

    if request.method == 'POST':
        playlist_form = PlaylistCreateForm(request.POST, request.FILES, instance=playlist)
        if playlist_form.is_valid():
            playlist = playlist_form.save()
            return redirect('main:playlist_detail', pk=pk)
    else:
        playlist_form = PlaylistCreateForm(instance=playlist)

    return render(request, 'main/update_playlist.html', {'playlist_form': playlist_form, 'playlist': playlist})

def DeletePlaylist(request, pk):
    playlist = get_object_or_404(Playlist, pk=pk)

    if request.method == 'POST':
        playlist.delete()
        return redirect('main:playlist_list')

    return render(request, 'main/delete_playlist.html', {'playlist': playlist})


@login_required
def DiscList(request):
    discs = Disc.objects.filter(user=request.user)
    return render(request, 'main/disc_list.html', {'discs': discs})

def CreateDisc(request):
    if request.method == 'POST':
        disc_form = DiscCreateForm(request.POST, request.FILES)

        if disc_form.is_valid():
            disc = disc_form.save(commit=False)
            disc.user = request.user
            disc.save()
            disc_form.save_m2m()
            return redirect('main:disc_list')
    else:
        disc_form = DiscCreateForm()

    return render(request, 'main/create_disc.html', {'disc_form': disc_form})


def DiscDetail(request, pk):
    disc = get_object_or_404(Disc, pk=pk)
    return render(request, 'main/disc_detail.html', {'disc': disc})

def UpdateDisc(request, pk):
    disc = get_object_or_404(Disc, pk=pk)

    if request.method == 'POST':
        disc_form = DiscCreateForm(request.POST, request.FILES, instance=disc)
        if disc_form.is_valid():
            disc = disc_form.save()
            return redirect('main:disc_list')
    else:
        disc_form = DiscCreateForm(instance=disc)

    return render(request, 'main/update_disc.html', {'disc_form': disc_form, 'disc': disc})

def DeleteDisc(request, pk):
    disc = get_object_or_404(Disc, pk=pk)

    if request.method == 'POST':
        disc.delete()
        return redirect('main:disc_list')

    return render(request, 'main/delete_disc.html', {'disc': disc})

def AlbumDetail(request, pk):
    album = get_object_or_404(Album, pk=pk)
    return render(request, 'main/album_detail.html', {'album': album})

def GenreDetail(request, pk):
    genre = get_object_or_404(Genre, pk=pk)
    artists_in_genre = Artist.objects.filter(genres=genre)
    albums_in_genre = Album.objects.filter(genres=genre)
    return render(request, 'main/genre_detail.html', 
                  {'genre': genre, 
                   'artists_in_genre': artists_in_genre,
                   'albums_in_genre': albums_in_genre})

def ArtistDetail(request, pk):
    artist = get_object_or_404(Artist, pk=pk)
    return render(request, 'main/artist_detail.html', {'artist': artist})

def CountryDetail(request, pk):
    country = get_object_or_404(Country, pk=pk)
    artists_in_country = Artist.objects.filter(nationality=country)
    return render(request, 'main/country_detail.html', {'country': country, 'artists_in_country': artists_in_country})

@login_required
def LikeList(request):
    liked_songs = Like.objects.filter(user=request.user)
    return render(request, 'main/like_list.html', {'likes': liked_songs})

@csrf_exempt
def CreateLike(request):
    if request.method == 'POST':
        user_id = request.POST.get('user')
        song_id = request.POST.get('song')
        Like.objects.create(user_id=user_id, song_id=song_id)

        return JsonResponse({'message': 'Like guardado con éxito'})
    else:
        return JsonResponse({'message': 'Método no permitido'}, status=405)

def SearchList(request):
    template_name = 'main/search.html'
    query = request.GET.get('q', '')

    # Buscar en Genre por su name
    genres = Genre.objects.filter(name__icontains=query)

    # Buscar en Artist por name, nickname, nationality, genres
    artists = Artist.objects.filter(
        Q(name__icontains=query) | Q(nickname__icontains=query) |
        Q(nationality__name__icontains=query) | Q(genres__name__icontains=query)
    ).distinct()

    # Buscar en Album por title, artists, genres
    albums = Album.objects.filter(
        Q(title__icontains=query) | Q(artists__name__icontains=query) |
        Q(genres__name__icontains=query)
    ).distinct()

    # Buscar en Song por title, genres, album
    songs = Song.objects.filter(
        Q(title__icontains=query) | Q(genres__name__icontains=query) |
        Q(album__title__icontains=query)
    ).distinct()

    context = {
        'query': query,
        'genres': genres,
        'artists': artists,
        'albums': albums,
        'songs': songs,
    }


templates/main/album_list.html
{% extends 'base/index.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'player.css' %}?{% now 'U' %}">
  <link rel="stylesheet" href="{% static 'search.css' %}?{% now 'U' %}">
  <link rel="stylesheet" href="{% static 'custom.css' %}?{% now 'U' %}">
{% endblock %}

{% block home %}
{% endblock %}

{% block main %}
  <div class="playlist__optionbar-container text-center">
    <div style='font-size: 18px'>
      <div class="homecontainer">
        <div class="category">
          {% for genre, albums in albums_by_genre.items %}
            <div class="catTitle">
              <span class='label catName underline-on-hover'>{{ genre }} albums</span>
              <a href="{% url 'main:album_list' %}">
                <span class='label seeall underline-on-hover'>SEE ALL</span>
              </a>
            </div>
            <div class="cardContainer">
              {% for album in albums %}
                <div class="card c1">
                    <div class="albumcover">
                    <img class="albumimg" src="{{ album.image.url }}" alt="{{ album.title }}">
                    <!--<div class="albumplay" onclick="playAlbum('{{ album.id }}')">-->
                    <!--<div class="albumplay" onclick="playAlbum('{{ album.id }}', '{{ album.get_all_video_ids|join:',' }}')">
                      <img src="https://cdn.discordapp.com/attachments/768083738848133130/769476261181128734/image_1.png" alt="">
                    </div>-->
                    <div class="albumplay" onclick="playAlbum('{{ album.id }}', ['{{ album.get_all_video_ids|join:',' }}'])">
                      <img src="https://cdn.discordapp.com/attachments/768083738848133130/769476261181128734/image_1.png" alt="">
                    </div>
                                      
                    </div>
                    <a href="{% url 'main:album_detail' pk=album.id %}">
                    <span class='label albumtitle bond-to-two-lines'>{{ album.title }}</span>
                    </a>
                    <a href="{% url 'main:artist_detail' pk=album.artists.first.id %}">
                    <span class='label albumauthor bond-to-two-lines'>
                        {% for artist in album.artists.all %}
                        By {{ artist.name }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </span>
                    </a>
                    <a href="{% url 'main:genre_detail' pk=album.genres.first.id %}">
                    <span class='label albumauthor bond-to-two-lines'>
                        {% for genre in album.genres.all %}
                        {{ genre.name }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </span>
                    </a>
                </div>
                {% endfor %}
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  {% endblock %}

templates/main/create_like.html
{% extends 'base/base.html' %}

{% block title %}
    Like Created
{% endblock title %}

{% block content %}
    <h2>Like Created Successfully</h2>
    <p>Thank you for liking this song!</p>
    <a href="{% url 'main:like_list' %}">Back to Some Page</a>
{% endblock content %}

templates/main/disc_list.html
{% extends 'base/index.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'playlist.css' %}?{% now 'U' %}">
{% endblock %}

{% block home %}
{% endblock %}

{% block main %}
<div class="playlist__banner">
  <div class="playlist__left">
    <div class="playlist__album">
      {% if user.profile.image %}
        <img src="{{ user.profile.image.url }}" class="playlist__img" alt="{{ user.username }}'s photo">
      {% else %}
        <img src="{% static 'default-profile-image.jpg' %}" class="playlist__img" alt="Default photo">
      {% endif %}
    </div>
  </div>
  <div class="playlist__right">
    <div style='text-transform: uppercase; font-weight: 700;font-size: 12px;'>
      {{ user.get_full_name }}
    </div>
    <div class="playlist__name">
      {{ user.username }}'s Disc
    </div>
      <a href="{% url 'main:create_disc' %}" class="profile">
        <span class='username hide-onhover'>Create</span>
        <span class='logout username'>Disc</span>
      </a>
  </div>
</div>

<div class="playlist__optionbar-container text-center">
  <div style='font-size: 18px'>
    <div class="homecontainer">
      <div class="category">
        <div class="catTitle">
          <span class='label catName underline-on-hover'> {{ user.username }}'s songs </span>
        </div>
        <div class="cardContainer">
          {% for disc in discs %}
            <div class="card c1">
              <div class="albumcover">
                {% if user.profile.image %}
                    <img class="albumimg" src="{{ user.profile.image.url }}" alt="{{ disc.title }}">
                {% else %}
                    <img class="albumimg" src="{% static 'default_profile_image.jpg' %}" alt="{{ disc.title }}">
                {% endif %} 
                <div class="albumplay" onclick='playSong("{{ disc.get_video_id }}")'>
                  <img src="https://cdn.discordapp.com/attachments/768083738848133130/769476261181128734/image_1.png" alt="">
                </div>
              </div>
              <a href="{% url 'main:disc_detail' pk=disc.id %}">
                <span class='label albumtitle bond-to-two-lines'>{{ disc.title }}</span>
              </a>
              <span class='label albumauthor bond-to-two-lines' style='margin-bottom: 5px;'>Created by: {{ user.username }}</span>
              <a href="{% url 'main:update_disc' pk=disc.id %}" class="profile" style='margin-bottom: 5px;'>
                <span class='username hide-onhover'>Update</span>
                <span class='logout username'>Song</span>
              </a>
              <a href="{% url 'main:delete_disc' pk=disc.id %}" class="profile" style='margin-bottom: 5px;'>
                <span class='username hide-onhover'>Delete</span>
                <span class='logout username'>Song</span>
              </a>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/main/genre_detail.html
{% extends 'base/index.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'playlist.css' %}?{% now 'U' %}">
  
{% endblock %}

{% block home %}
{% endblock %}

{% block main %}
<div class="playlist__banner">
    <div class="playlist__right">
        <div class="playlist__name">
            {{ genre.name }}
        </div>
        <div style='font-weight: 700; font-size: 12px;'>
          {{ genre.description }}
      </div>
    </div>
</div>

<div class="playlist__optionbar-container text-center">
  <div style='font-size: 18px'>
    <div class="homecontainer">
      <div class="category">
        <div class="catTitle">
          <span class='label catName underline-on-hover'> {{ genre.name }}'s artists </span>
          <a href="{% url 'main:album_list' %}">
            <span class='label seeall underline-on-hover'>SEE ALL</span>
          </a>
        </div>
        <div class="cardContainer">
          {% for artist in artists_in_genre %}
            <div class="card c1">
              <div class="albumcover">
                <img class="albumimg" src="{% if artist.image %}{{ artist.image.url }}{% else %}{% static 'profiles/NoProfile.jpg' %}{% endif %}" alt="{{ artist.name }}'s photo">
              </div>
              <a href="{% url 'main:artist_detail' pk=artist.id %}">
                <span class='label albumtitle bond-to-two-lines'>{{ artist.name }}</span>
              </a>
              <span class='label albumauthor bond-to-two-lines'>
                {% for genre in artist.genres.all %}
                  {{ genre.name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
              </span>
            </div>
          {% endfor %}
        </div>
      </div>
      <div class="category">
        <div class="catTitle">
          <span class='label catName underline-on-hover'> {{ genre.name }}'s albums </span>
          <a href="{% url 'main:album_list' %}">
            <span class='label seeall underline-on-hover'>SEE ALL</span>
          </a>
        </div>
        <div class="cardContainer">
          {% for album in albums_in_genre %}
            <div class="card c1">
              <div class="albumcover">
                <img class="albumimg" src="{{ album.image.url }}" alt="{{ album.title }}">
                <!-- Botón de reproducción -->
                <div class="albumplay" onclick="playAlbum('{{ album.id }}', ['{{ album.get_all_video_ids|join:',' }}'])">
                  <img src="https://cdn.discordapp.com/attachments/768083738848133130/769476261181128734/image_1.png" alt="">
                </div>
              </div>
              <a href="{% url 'main:album_detail' pk=album.id %}">
                <span class='label albumtitle bond-to-two-lines'>{{ album.title }}</span>
              </a>
              <a href="{% url 'main:artist_detail' pk=album.artists.first.id %}">
                <span class='label albumauthor bond-to-two-lines'>
                  {% for artist_in_album in album.artists.all %}
                    By {{ artist_in_album.name }}{% if not forloop.last %}, {% endif %}
                  {% endfor %}
                </span>
              </a>
              <a href="{% url 'main:genre_detail' pk=album.genres.first.id %}">
                <span class='label albumauthor bond-to-two-lines'>
                  {% for genre_in_album in album.genres.all %}
                    {{ genre_in_album.name }}{% if not forloop.last %}, {% endif %}
                  {% endfor %}
                </span>
              </a>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}


templates/main/playlist_list.html
{% extends 'base/index.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'playlist.css' %}?{% now 'U' %}">
{% endblock %}

{% block home %}
{% endblock %}

{% block iframe %}
 
{% endblock %}

{% block main %}
<div class="playlist__banner">
  <div class="playlist__left">
    <div class="playlist__album">
      {% if user.profile.image %}
        <img src="{{ user.profile.image.url }}" class="playlist__img" alt="{{ user.username }}'s photo">
      {% else %}
        <img src="{% static 'default-profile-image.jpg' %}" class="playlist__img" alt="Default photo">
      {% endif %}
    </div>
  </div>
  <div class="playlist__right">
    <div style='text-transform: uppercase; font-weight: 700;font-size: 12px;'>
      {{ user.get_full_name }}
    </div>
    <div class="playlist__name">
      {{ user.username }}'s Library
    </div>
      <a href="{% url 'main:create_playlist' %}" class="profile">
        <span class='username hide-onhover'>Create</span>
        <span class='logout username'>Playlist</span>
      </a>
  </div>
</div>

<div class="playlist__optionbar-container text-center">
  <div style='font-size: 18px'>
    <div class="homecontainer">
      <div class="category">
        <div class="catTitle">
          <span class='label catName underline-on-hover'> {{ user.username }}'s playlists </span>
        </div>
        <div class="cardContainer">
          {% for playlist in playlists %}
            <div class="card c1">
              <div class="albumcover">
                  {% if playlist.user.profile.image %}
                      <img class="albumimg" src="{{ playlist.user.profile.image.url }}" alt="{{ playlist.title }}">
                  {% else %}
                      <img class="albumimg" src="{% static 'default_profile_image.jpg' %}" alt="{{ playlist.title }}">
                  {% endif %} 
                <div class="albumplay" onclick='playPlaylist("{{ forloop.counter0 }}","{{ playlist.id }}")'>
                  <img src="https://cdn.discordapp.com/attachments/768083738848133130/769476261181128734/image_1.png" alt="">
                </div>
              </div>
              <a href="{% url 'main:playlist_detail' pk=playlist.id %}">
                <span class='label albumtitle bond-to-two-lines'>{{ playlist.title }}</span>
              </a>
              <span class='label albumauthor bond-to-two-lines' style='margin-bottom: 5px;'>Created by: {{ playlist.user.username }}</span>
              <a href="{% url 'main:update_playlist' pk=playlist.id %}" class="profile" style='margin-bottom: 5px;'>
                <span class='username hide-onhover'>Update</span>
                <span class='logout username'>Playlist</span>
              </a>
              <a href="{% url 'main:delete_playlist' pk=playlist.id %}" class="profile" style='margin-bottom: 5px;'>
                <span class='username hide-onhover'>Delete</span>
                <span class='logout username'>Playlist</span>
              </a>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}
